;website
upload_max_filesize = 8M
post_max_size = 8M
date.timezone = "Europe/Warsaw"

; Security
disable_functions=exec,system,shell_exec,passthru,proc_open
expose_php=Off
session.name = User

; Performance (OpCache)
;opcache.enable=1
;opcache.memory_consumption=128
;opcache.interned_strings_buffer=8
;opcache.validate_timestamps=1 ; Set to 0 in Production

