services:
  web-geobecnosc:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ../Frontend:/Frontend
      - ../Backend:/Backend
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      TZ: Europe/Warsaw
    depends_on:
      - php-geobecnosc

  php-geobecnosc:
    build: ./php
    environment:
      TZ: Europe/Warsaw
    volumes:
      - ../Frontend:/Frontend
      - ../Backend:/Backend
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    restart: always

  db-geobecnosc:
    build: ./db
    environment:
      MARIADB_DATABASE: geobecnosc
      MARIADB_USER: User
      MARIADB_PASSWORD: aMgtm48OBi0cxEvG5I8MQBj4oOsG2asakcEpymZySn3i8SyNSzDzOjWIkUfqxwMp
      MARIADB_ROOT_PASSWORD: aMgtm48OBi0cxEvG5I8MQBj4oOsG2asakcEpymZySn3i8SyNSzDzOjWIkUfqxwMp
      TZ: Europe/Warsaw
    volumes:
      - ./db/geobecnosc.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data: