user nginx;
worker_processes auto;
pid /run/nginx.pid;


events {
        worker_connections 768;
        # multi_accept on;
}

http {

        sendfile on;
        tcp_nopush on;
        client_max_body_size 8M;
        types_hash_max_size 2048;
        server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        gzip on;

        access_log /Backend/nginx-access.log;
        error_log /Backend/nginx-error.log;

        # gzip_vary on;
        # gzip_proxied any;
        # gzip_comp_level 6;
        # gzip_buffers 16 8k;
        # gzip_http_version 1.1;
        # gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        ##
        # Virtual Host Configs
        ##

        server {
                listen 80 default_server;
                listen [::]:80 default_server;

                root /Frontend;
                index index.html;

                server_name geobecnosc;

                error_page 404 /404.html;
                error_page 500 502 503 504 /500.html;
                absolute_redirect off;

                location = /404.html {
                        internal;
                        alias /Backend/404.html;
                }
                
                location = /500.html {
                        internal;
                        alias /Backend/500.html;
                }

                location = /api {
                        include fastcgi_params;
                        fastcgi_pass php-geobecnosc:9000;
                        fastcgi_param SCRIPT_FILENAME /Backend/api.php;
                }

                location ~ \.php$ {
                        return 404;
                }

                location / {
                        try_files $uri $uri/index.html =404;
                }

        }
}